/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infopharma.acc;

import infopharma.Validator;
import infopharma.data.AccountDBAccess;
import infopharma.data.MerchantAccount;
import infopharma.data.UserAccount;
import infopharma.data.MiscDBAccess;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author Abdullah
 */
public class ViewRestoreAccount extends InfoPharmaPanel {
    
    private static InfoPharmaFrame frame;
    private AccountDBAccess accountDB;
    private ArrayList<MerchantAccount> merchants;
    private HashMap<Integer, String> accountStatuses;
	
    public ViewRestoreAccount(InfoPharmaFrame mainMenuFrame) {
        accountDB = new AccountDBAccess();
        accountStatuses = accountDB.getAccountStatuses();
        initComponents();
        setFrame(mainMenuFrame);
        lblError.setVisible(false);
        radioBtnGroup.add(radioBtnActive);
        radioBtnGroup.add(radioBtnSuspended);
        radioBtnGroup.add(radioBtnDefault);
        populateComboMerchants();
        this.setVisible(true);
    }

    public static InfoPharmaFrame getFrame() {
        return InfoPharmaPanel.getFrame();
    }

    public static void setFrame(InfoPharmaFrame frame) {
        InfoPharmaPanel.setFrame(frame);
    }
    
    public void populateComboMerchants() {
        merchants = accountDB.getAllMerchants();
        for(MerchantAccount merchant : merchants) {
            comboMerchants.addItem(merchant.getCompany());
        }
    }
    
    public void populateMerchantDetails() {
        MerchantAccount merchant = getSelectedMerchant();
        String status = getAccountStatus(merchant).toLowerCase();
        if(status.contains("default")) {
            radioBtnDefault.setSelected(true);
        } else if(status.contains("active")) {
            radioBtnActive.setSelected(true);
        } else if(status.contains("suspend")) {
            radioBtnSuspended.setSelected(true);
        }
    }
    
    public String getAccountStatus(MerchantAccount merchant) {
        return accountStatuses.get(merchant.getAccountStatusID());
    }
    
    public int getAccountStatusID(String status) {
        Iterator it = accountStatuses.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry)it.next();
            if(pairs.getValue().toString().toLowerCase().contains(status)) {
                return (Integer) pairs.getKey();
            }
        }
        return -1;
    }
    
    public int getSelectedAccountStatus() {
        int statusID = -1;
        if(radioBtnActive.isSelected()) {
            statusID = getAccountStatusID("active");
        } else if(radioBtnSuspended.isSelected()) {
            statusID = getAccountStatusID("suspend");
        } else if(radioBtnDefault.isSelected()) {
            statusID = getAccountStatusID("default");
        }
        return statusID;
    }
    
    public MerchantAccount getSelectedMerchant() {
        String company = comboMerchants.getSelectedItem().toString();
        MerchantAccount merchant = null;
        for(int i=0; i<merchants.size(); i++) {
            if(merchants.get(i).getCompany().equals(company)) {
                merchant = merchants.get(i);
                break;
            }
        }
        return merchant;
    }
    
    public void updateMerchantStatus() {
        MerchantAccount merchant = getSelectedMerchant();
        int statusID = getSelectedAccountStatus();
        if(accountDB.updateMerchantStatus(merchant, statusID)) {
            mainMenu();
        } else {
            System.err.println("Shit fucked up.");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        layeredPanel = new javax.swing.JLayeredPane();
        lblError = new javax.swing.JLabel();
        comboMerchants = new javax.swing.JComboBox();
        radioBtnSuspended = new javax.swing.JRadioButton();
        radioBtnDefault = new javax.swing.JRadioButton();
        radioBtnActive = new javax.swing.JRadioButton();
        imageLabel = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        btnMainMenu1 = new javax.swing.JButton();

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/acc/images/error.png"))); // NOI18N
        lblError.setBounds(10, 520, 820, 40);
        layeredPanel.add(lblError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboMerchants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMerchantsActionPerformed(evt);
            }
        });
        comboMerchants.setBounds(30, 130, 270, 27);
        layeredPanel.add(comboMerchants, javax.swing.JLayeredPane.DEFAULT_LAYER);
        radioBtnSuspended.setBounds(30, 233, 30, 30);
        layeredPanel.add(radioBtnSuspended, javax.swing.JLayeredPane.DEFAULT_LAYER);
        radioBtnDefault.setBounds(30, 263, 30, 30);
        layeredPanel.add(radioBtnDefault, javax.swing.JLayeredPane.DEFAULT_LAYER);
        radioBtnActive.setBounds(30, 203, 30, 30);
        layeredPanel.add(radioBtnActive, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/acc/images/restoreaccount.png"))); // NOI18N
        imageLabel.setBounds(0, 0, 1100, 570);
        layeredPanel.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        btnGo.setBounds(1020, 70, 80, 470);
        layeredPanel.add(btnGo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMainMenu.setText("main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        btnMainMenu.setBounds(1010, 10, 80, 50);
        layeredPanel.add(btnMainMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMainMenu1.setText("main menu");
        btnMainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenu1ActionPerformed(evt);
            }
        });
        btnMainMenu1.setBounds(1020, 540, 80, 29);
        layeredPanel.add(btnMainMenu1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 570, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        this.getFrame().setPanel(new ViewMainMenu(this.getFrame()));
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void comboMerchantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMerchantsActionPerformed
        populateMerchantDetails();
    }//GEN-LAST:event_comboMerchantsActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        updateMerchantStatus();
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnMainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenu1ActionPerformed
        mainMenu();
    }//GEN-LAST:event_btnMainMenu1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnMainMenu1;
    private javax.swing.JComboBox comboMerchants;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JRadioButton radioBtnActive;
    private javax.swing.JRadioButton radioBtnDefault;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JRadioButton radioBtnSuspended;
    // End of variables declaration//GEN-END:variables
}
