/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infopharma.cat;

import infopharma.Validator;
import infopharma.acc.InfoPharmaFrame;
import infopharma.acc.InfoPharmaPanel;
import infopharma.acc.ViewMainMenu;
import infopharma.data.CatDBAccess;
import infopharma.data.UserAccount;
import infopharma.data.MiscDBAccess;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author Abdullah
 */
public class ViewStockMaintenance extends InfoPharmaPanel{
    private static InfoPharmaFrame frame;
    private CatDBAccess catDBAccess;
    private HashMap<Integer, String> products;
	
    public ViewStockMaintenance(InfoPharmaFrame mainMenuFrame)
    {
        catDBAccess = new CatDBAccess();
        initComponents();
        setFrame(mainMenuFrame);
        lblError.setVisible(false);
        populateComboProducts();
        this.setVisible(true);
    }
    
    public void populateComboProducts()
    {
        ddlProducts.removeAllItems();
        products = catDBAccess.getProducts();
        for(String product : products.values())
        {
            ddlProducts.addItem(product);
        }
        ddlProducts.updateUI();
    }

    public static InfoPharmaFrame getFrame() 
    {
        return InfoPharmaPanel.getFrame();
    }

    public static void setFrame(InfoPharmaFrame frame) 
    {
        InfoPharmaPanel.setFrame(frame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPanel = new javax.swing.JLayeredPane();
        ddlProducts = new javax.swing.JComboBox();
        txtAdditionalStock = new javax.swing.JFormattedTextField();
        txtCurrentStock = new javax.swing.JFormattedTextField();
        lblError = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        ddlProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlProductsActionPerformed(evt);
            }
        });
        ddlProducts.setBounds(40, 140, 250, 27);
        layeredPanel.add(ddlProducts, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAdditionalStock.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txtAdditionalStock.setBounds(40, 300, 250, 28);
        layeredPanel.add(txtAdditionalStock, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtCurrentStock.setEditable(false);
        txtCurrentStock.setBounds(30, 218, 260, 30);
        layeredPanel.add(txtCurrentStock, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/acc/images/error.png"))); // NOI18N
        lblError.setBounds(10, 520, 820, 40);
        layeredPanel.add(lblError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/cat/images/stockmaintenance.png"))); // NOI18N
        imageLabel.setBounds(0, 0, 1100, 570);
        layeredPanel.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMainMenu.setText("main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        btnMainMenu.setBounds(1010, 10, 80, 50);
        layeredPanel.add(btnMainMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGo.setText("jButton1");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        btnGo.setBounds(1020, 70, 80, 470);
        layeredPanel.add(btnGo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCancel.setText("jButton1");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.setBounds(1017, 540, 80, 29);
        layeredPanel.add(btnCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 570, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        this.getFrame().setPanel(new ViewMainMenu(this.getFrame()));
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        if(updateStock())
        {
            goToMainMenu();
        }
        
    }//GEN-LAST:event_btnGoActionPerformed

    public boolean updateStock()
    {
        if(isValidStockAmount())
        {
            System.out.println("selected product:" +ddlProducts.getSelectedItem().toString());
            System.out.println("additional amount:" +txtAdditionalStock.getValue().toString());
            catDBAccess.updateStock(ddlProducts.getSelectedItem().toString(), txtAdditionalStock.getValue().toString());
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public boolean isValidStockAmount()
    {
        lblError.setVisible(false);
        try
        {
            int additionalStock = Integer.parseInt(txtAdditionalStock.getValue().toString());
            if(additionalStock >= 0)
            {
                return true;
            }
            else
            {
               System.out.println("Error!!");
                lblError.setText("Please enter a valid stock amount");
                lblError.setVisible(true); 
            }
        }
        catch(Exception e)
        {
            System.out.println("Error!!");
            lblError.setText("Please enter a valid stock amount");
            lblError.setVisible(true);
           
        }
        return false;
    }
    
    private void ddlProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlProductsActionPerformed
        System.out.println("Changed selected");
        int currentStock = catDBAccess.getProductStock(ddlProducts.getSelectedItem().toString());
        txtCurrentStock.setText(""+currentStock);
    }//GEN-LAST:event_ddlProductsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        goToMainMenu();
    }//GEN-LAST:event_btnCancelActionPerformed

    public void goToMainMenu()
    {
        this.getFrame().setPanel(new ViewMainMenu(this.getFrame()));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JComboBox ddlProducts;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JFormattedTextField txtAdditionalStock;
    private javax.swing.JFormattedTextField txtCurrentStock;
    // End of variables declaration//GEN-END:variables
}
