/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infopharma;



/**
 *
 * @author Abdullah
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        logo.setVisible(false);
        loadingBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ipos = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ipos.setFont(new java.awt.Font("Arial", 3, 60)); // NOI18N
        ipos.setForeground(new java.awt.Color(215, 215, 215));
        ipos.setBounds(270, 130, 160, 80);
        jLayeredPane1.add(ipos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        loadingBar.setBackground(new java.awt.Color(51, 51, 51));
        loadingBar.setForeground(new java.awt.Color(9, 187, 187));
        loadingBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loadingBar.setBounds(20, 200, 380, 20);
        jLayeredPane1.add(loadingBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/logo.png"))); // NOI18N
        logo.setBounds(260, 60, 170, 140);
        jLayeredPane1.add(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/loadingscreen.png"))); // NOI18N
        background.setBounds(0, 0, 490, 230);
        jLayeredPane1.add(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-494)/2, (screenSize.height-230)/2, 494, 230);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
                //getP();
                
            }
        });
    }
    
    public void updateIPOS()
    {
        if(loadingBar.getValue() < 10)
        {
        ipos.setText("0"+loadingBar.getValue()+"%");
        }
        else
        {
            ipos.setText(loadingBar.getValue()+"%");
        }      
        ipos.updateUI();
    }
    
    
    public void animateLogo()
    {
        logo.setVisible(true);
        boolean canMove = true;
        while(canMove)
        {
            try 
            {
                Thread.currentThread().sleep(25);
                logo.setLocation(logo.getLocation().x - 10, logo.getLocation().y);
                logo.updateUI();
                if(logo.getLocation().x < 30)
                {
                    canMove = false;
                }
            }
            catch (Exception e)
            {}
            
        }
    }
    
    public void animateIPOS()
    {
        ipos.setVisible(true);
    }
    
    
    
    public void animateLoadingBar()
    {
        loadingBar.setVisible(true);
        int delayFactor = 400;
        while(loadingBar.getValue() < 100)
        {
            int random = (int) (delayFactor * Math.random());
            try 
            {
                Thread.sleep(random);
                int value = (int)(loadingBar.getValue() + (30 * Math.random()));
                loadingBar.setValue(value);
                updateIPOS();
            } 
            catch (Exception ex) 
            {
                // do nothing
            }
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel ipos;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
