/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infopharma.order;

import infopharma.Validator;
import infopharma.acc.InfoPharmaFrame;
import infopharma.acc.InfoPharmaPanel;
import infopharma.data.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdullah
 */
public class ViewOutstandingBalances extends InfoPharmaPanel{
    
    private static InfoPharmaFrame frame;
    private AccountDBAccess dbAccount;
    private OrderDBAccess dbOrder;
    private ArrayList<MerchantAccount> merchants;
    private DefaultTableModel model;
	
    public ViewOutstandingBalances(InfoPharmaFrame mainMenuFrame) {
        dbAccount = new AccountDBAccess();
        dbOrder = new OrderDBAccess();
        merchants = dbAccount.getAllMerchants();
        initComponents();
        setFieldsOpaque();
        model = (DefaultTableModel) tableUnpaidOrders.getModel();
        populateComboMerchants();
        setFrame(mainMenuFrame);
        lblError.setVisible(false);
        this.setVisible(true);
    }

    public static InfoPharmaFrame getFrame() {
        return InfoPharmaPanel.getFrame();
    }

    public static void setFrame(InfoPharmaFrame frame) {
        InfoPharmaPanel.setFrame(frame);
    }
    
    public void setFieldsOpaque() {
        JTextField[] fields = {textBalances, textCredit};
        setFieldsOpaque(fields);
    }
    
    public void populateComboMerchants() {
        comboMerchants.removeAllItems();
        for(MerchantAccount merchant : merchants) {
            comboMerchants.addItem(merchant.getAccountNumber());
        }
    }
    
    public MerchantAccount getSelectedMerchant() {
        int id = Integer.parseInt(comboMerchants.getSelectedItem().toString());
        for(MerchantAccount merchant : merchants) {
            if(merchant.getAccountNumber() == id) {
                return merchant;
            }
        }
        return null;
    }
    
    public void getOutstandingBalances() {
        MerchantAccount merchant = getSelectedMerchant();
        int accountNumber = merchant.getAccountNumber();
        if(merchant != null) {
            ArrayList<Order> unpaidOrders = dbOrder.getUnpaidMerchantOrders(accountNumber);
            displayUnpaidBalances(unpaidOrders);
        }
    }

    public void displayUnpaidBalances(ArrayList<Order> unpaidOrders) {
        clearTable();
        updateTable(unpaidOrders);
        updateFields();
    }
    
    public void clearTable() {
        for(int i = model.getRowCount() - 1; i >=0; i--) {
            model.removeRow(i);
        }
    }
    
    public void updateTable(ArrayList<Order> unpaidOrders) {
        for(Order order : unpaidOrders) {
            int orderId = order.getID();
            String date = order.getDate();
            double total = order.getTotal();
            model.insertRow(0, new Object[]{orderId, date, total});
        }
    }
    
    public void updateFields() {
        int unpaidBalancesAmnt = model.getRowCount();
        textBalances.setText(unpaidBalancesAmnt + "");
        MerchantAccount merchant = getSelectedMerchant();
        double creditAvail = merchant.getCreditLimit() - merchant.getBalance();
        textCredit.setText(creditAvail + "");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPanel = new javax.swing.JLayeredPane();
        lblError = new javax.swing.JLabel();
        comboMerchants = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUnpaidOrders = new javax.swing.JTable();
        textCredit = new javax.swing.JTextField();
        textBalances = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/acc/images/error.png"))); // NOI18N
        lblError.setBounds(10, 520, 820, 40);
        layeredPanel.add(lblError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboMerchants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMerchantsActionPerformed(evt);
            }
        });
        comboMerchants.setBounds(30, 130, 270, 40);
        layeredPanel.add(comboMerchants, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tableUnpaidOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Date", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableUnpaidOrders);

        jScrollPane1.setBounds(30, 210, 610, 250);
        layeredPanel.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textCredit.setEditable(false);
        textCredit.setBounds(380, 500, 250, 28);
        layeredPanel.add(textCredit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textBalances.setEditable(false);
        textBalances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBalancesActionPerformed(evt);
            }
        });
        textBalances.setBounds(40, 500, 250, 28);
        layeredPanel.add(textBalances, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/order/images/outstandingbalances.png"))); // NOI18N
        imageLabel.setBounds(0, 0, 1100, 570);
        layeredPanel.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        btnOk.setBounds(1010, 70, 90, 500);
        layeredPanel.add(btnOk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMainMenu.setText("main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        btnMainMenu.setBounds(1010, 10, 80, 50);
        layeredPanel.add(btnMainMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 570, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        mainMenu();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void comboMerchantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMerchantsActionPerformed
        getOutstandingBalances();
    }//GEN-LAST:event_comboMerchantsActionPerformed

    private void textBalancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBalancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBalancesActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        mainMenu();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox comboMerchants;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tableUnpaidOrders;
    private javax.swing.JTextField textBalances;
    private javax.swing.JTextField textCredit;
    // End of variables declaration//GEN-END:variables
}
