/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infopharma.order;

import infopharma.Validator;
import infopharma.acc.InfoPharmaFrame;
import infopharma.acc.InfoPharmaPanel;
import infopharma.acc.ViewMainMenu;
import infopharma.data.UserAccount;
import infopharma.data.MiscDBAccess;
import infopharma.data.OrderDBAccess;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author Abdullah
 */
public class ViewUpdateOrderStatus extends InfoPharmaPanel {
    
    private static InfoPharmaFrame frame;
    private OrderDBAccess dbOrder;
	
    public ViewUpdateOrderStatus(InfoPharmaFrame mainMenuFrame) {
        dbOrder = new OrderDBAccess();
        initComponents();
        setFrame(mainMenuFrame);
        lblError.setVisible(false);
        popualateComboOrderID();
        this.setVisible(true);
    }

    public static InfoPharmaFrame getFrame() {
        return InfoPharmaPanel.getFrame();
    }

    public static void setFrame(InfoPharmaFrame frame) {
        InfoPharmaPanel.setFrame(frame);
    }
    
    public void popualateComboOrderID() {
        ArrayList<Integer> ordersArray = dbOrder.getAllOrderIDs();
        for(int orderID : ordersArray) {
            comboOrderID.addItem(orderID);
        }
    }
    
    public void setOrderStatus() {
        String orderStatus = getOrderStatus();
        textOrderStatus.setText(orderStatus);
        setRadioBtnOrderStatus(orderStatus);
    }
    
    public String getOrderStatus() {
        int orderID = Integer.parseInt(comboOrderID.getSelectedItem().toString());
        String orderStatus = dbOrder.getOrderStatus(orderID);
        return orderStatus;
    }
    
    public void setRadioBtnOrderStatus(String orderStatus) {
        if(orderStatus.toLowerCase().contains("process")) {
            radioBtnProcessed.setSelected(true);
        }else if(orderStatus.toLowerCase().contains("accept")) {
            radioBtnAccepted.setSelected(true);
        }else if(orderStatus.toLowerCase().contains("dispatch")) {
            radioBtnDispatched.setSelected(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        layeredPanel = new javax.swing.JLayeredPane();
        lblError = new javax.swing.JLabel();
        comboOrderID = new javax.swing.JComboBox();
        textOrderStatus = new javax.swing.JTextField();
        radioBtnProcessed = new javax.swing.JRadioButton();
        radioBtnAccepted = new javax.swing.JRadioButton();
        radioBtnDispatched = new javax.swing.JRadioButton();
        imageLabel = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/acc/images/error.png"))); // NOI18N
        lblError.setBounds(10, 520, 820, 40);
        layeredPanel.add(lblError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrderIDActionPerformed(evt);
            }
        });
        comboOrderID.setBounds(30, 140, 270, 27);
        layeredPanel.add(comboOrderID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textOrderStatus.setEditable(false);
        textOrderStatus.setBounds(40, 220, 250, 28);
        layeredPanel.add(textOrderStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioBtnGroup.add(radioBtnProcessed);
        radioBtnProcessed.setBounds(new java.awt.Rectangle(28, 319, 30, 23));
        radioBtnProcessed.setBounds(30, 320, 30, 23);
        layeredPanel.add(radioBtnProcessed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioBtnGroup.add(radioBtnAccepted);
        radioBtnAccepted.setBounds(new java.awt.Rectangle(28, 289, 30, 23));
        radioBtnAccepted.setBounds(30, 290, 30, 23);
        layeredPanel.add(radioBtnAccepted, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioBtnGroup.add(radioBtnDispatched);
        radioBtnDispatched.setBounds(new java.awt.Rectangle(28, 349, 30, 23));
        radioBtnDispatched.setBounds(30, 350, 30, 23);
        layeredPanel.add(radioBtnDispatched, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infopharma/order/images/updateorderstatus.png"))); // NOI18N
        imageLabel.setBounds(0, 0, 1100, 570);
        layeredPanel.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMainMenu.setText("main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        btnMainMenu.setBounds(1010, 10, 80, 50);
        layeredPanel.add(btnMainMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layeredPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 570, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        this.getFrame().setPanel(new ViewMainMenu(this.getFrame()));
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void comboOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrderIDActionPerformed
        setOrderStatus();
    }//GEN-LAST:event_comboOrderIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JComboBox comboOrderID;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JRadioButton radioBtnAccepted;
    private javax.swing.JRadioButton radioBtnDispatched;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JRadioButton radioBtnProcessed;
    private javax.swing.JTextField textOrderStatus;
    // End of variables declaration//GEN-END:variables
}
;